# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
release:
  # Repo in which the release will be created.
  github:
    owner: andig
    name: evcc
before:
  hooks:
    # you may remove this if you don't need go generate
    - make assets
builds:
- id: evcc
  # Path to main.go file or main package.
  main: main.go
  ldflags:
  - -X github.com/andig/evcc/server.Version={{.Version}} -X github.com/andig/evcc/server.Commit={{.ShortCommit}}
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm
  goarm:
  - "6"
archives:
  - builds:
    - evcc
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
    format: tar.gz
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^chore'
    - '^bump'
    - '^docs:'
    - '^test:'
