// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: vehicle/skoda/pb/checkin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChromeBuildProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      *int32                 `protobuf:"varint,1,opt,name=platform" json:"platform,omitempty"`
	ChromeVersion *string                `protobuf:"bytes,2,opt,name=chrome_version,json=chromeVersion" json:"chrome_version,omitempty"`
	Channel       *int32                 `protobuf:"varint,3,opt,name=channel" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChromeBuildProto) Reset() {
	*x = ChromeBuildProto{}
	mi := &file_vehicle_skoda_pb_checkin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChromeBuildProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChromeBuildProto) ProtoMessage() {}

func (x *ChromeBuildProto) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_skoda_pb_checkin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChromeBuildProto.ProtoReflect.Descriptor instead.
func (*ChromeBuildProto) Descriptor() ([]byte, []int) {
	return file_vehicle_skoda_pb_checkin_proto_rawDescGZIP(), []int{0}
}

func (x *ChromeBuildProto) GetPlatform() int32 {
	if x != nil && x.Platform != nil {
		return *x.Platform
	}
	return 0
}

func (x *ChromeBuildProto) GetChromeVersion() string {
	if x != nil && x.ChromeVersion != nil {
		return *x.ChromeVersion
	}
	return ""
}

func (x *ChromeBuildProto) GetChannel() int32 {
	if x != nil && x.Channel != nil {
		return *x.Channel
	}
	return 0
}

type AndroidCheckinProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *int32                 `protobuf:"varint,12,opt,name=type" json:"type,omitempty"`
	ChromeBuild   *ChromeBuildProto      `protobuf:"bytes,6,opt,name=chrome_build,json=chromeBuild" json:"chrome_build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AndroidCheckinProto) Reset() {
	*x = AndroidCheckinProto{}
	mi := &file_vehicle_skoda_pb_checkin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AndroidCheckinProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndroidCheckinProto) ProtoMessage() {}

func (x *AndroidCheckinProto) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_skoda_pb_checkin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndroidCheckinProto.ProtoReflect.Descriptor instead.
func (*AndroidCheckinProto) Descriptor() ([]byte, []int) {
	return file_vehicle_skoda_pb_checkin_proto_rawDescGZIP(), []int{1}
}

func (x *AndroidCheckinProto) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *AndroidCheckinProto) GetChromeBuild() *ChromeBuildProto {
	if x != nil {
		return x.ChromeBuild
	}
	return nil
}

type AndroidCheckinRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               *uint64                `protobuf:"fixed64,1,opt,name=id" json:"id,omitempty"`
	UserSerialNumber *int32                 `protobuf:"varint,2,opt,name=user_serial_number,json=userSerialNumber" json:"user_serial_number,omitempty"`
	Checkin          *AndroidCheckinProto   `protobuf:"bytes,4,opt,name=checkin" json:"checkin,omitempty"`
	SecurityToken    *uint64                `protobuf:"fixed64,5,opt,name=security_token,json=securityToken" json:"security_token,omitempty"`
	Version          *int32                 `protobuf:"varint,6,opt,name=version" json:"version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AndroidCheckinRequest) Reset() {
	*x = AndroidCheckinRequest{}
	mi := &file_vehicle_skoda_pb_checkin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AndroidCheckinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndroidCheckinRequest) ProtoMessage() {}

func (x *AndroidCheckinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_skoda_pb_checkin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndroidCheckinRequest.ProtoReflect.Descriptor instead.
func (*AndroidCheckinRequest) Descriptor() ([]byte, []int) {
	return file_vehicle_skoda_pb_checkin_proto_rawDescGZIP(), []int{2}
}

func (x *AndroidCheckinRequest) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *AndroidCheckinRequest) GetUserSerialNumber() int32 {
	if x != nil && x.UserSerialNumber != nil {
		return *x.UserSerialNumber
	}
	return 0
}

func (x *AndroidCheckinRequest) GetCheckin() *AndroidCheckinProto {
	if x != nil {
		return x.Checkin
	}
	return nil
}

func (x *AndroidCheckinRequest) GetSecurityToken() uint64 {
	if x != nil && x.SecurityToken != nil {
		return *x.SecurityToken
	}
	return 0
}

func (x *AndroidCheckinRequest) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

type AndroidCheckinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AndroidId     *uint64                `protobuf:"fixed64,7,opt,name=android_id,json=androidId" json:"android_id,omitempty"`
	SecurityToken *uint64                `protobuf:"fixed64,8,opt,name=security_token,json=securityToken" json:"security_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AndroidCheckinResponse) Reset() {
	*x = AndroidCheckinResponse{}
	mi := &file_vehicle_skoda_pb_checkin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AndroidCheckinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndroidCheckinResponse) ProtoMessage() {}

func (x *AndroidCheckinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_skoda_pb_checkin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndroidCheckinResponse.ProtoReflect.Descriptor instead.
func (*AndroidCheckinResponse) Descriptor() ([]byte, []int) {
	return file_vehicle_skoda_pb_checkin_proto_rawDescGZIP(), []int{3}
}

func (x *AndroidCheckinResponse) GetAndroidId() uint64 {
	if x != nil && x.AndroidId != nil {
		return *x.AndroidId
	}
	return 0
}

func (x *AndroidCheckinResponse) GetSecurityToken() uint64 {
	if x != nil && x.SecurityToken != nil {
		return *x.SecurityToken
	}
	return 0
}

var File_vehicle_skoda_pb_checkin_proto protoreflect.FileDescriptor

const file_vehicle_skoda_pb_checkin_proto_rawDesc = "" +
	"\n" +
	"\x1evehicle/skoda/pb/checkin.proto\x12\x05skoda\"o\n" +
	"\x10ChromeBuildProto\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\x05R\bplatform\x12%\n" +
	"\x0echrome_version\x18\x02 \x01(\tR\rchromeVersion\x12\x18\n" +
	"\achannel\x18\x03 \x01(\x05R\achannel\"e\n" +
	"\x13AndroidCheckinProto\x12\x12\n" +
	"\x04type\x18\f \x01(\x05R\x04type\x12:\n" +
	"\fchrome_build\x18\x06 \x01(\v2\x17.skoda.ChromeBuildProtoR\vchromeBuild\"\xcc\x01\n" +
	"\x15AndroidCheckinRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x06R\x02id\x12,\n" +
	"\x12user_serial_number\x18\x02 \x01(\x05R\x10userSerialNumber\x124\n" +
	"\acheckin\x18\x04 \x01(\v2\x1a.skoda.AndroidCheckinProtoR\acheckin\x12%\n" +
	"\x0esecurity_token\x18\x05 \x01(\x06R\rsecurityToken\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\"^\n" +
	"\x16AndroidCheckinResponse\x12\x1d\n" +
	"\n" +
	"android_id\x18\a \x01(\x06R\tandroidId\x12%\n" +
	"\x0esecurity_token\x18\b \x01(\x06R\rsecurityTokenB*Z(github.com/evcc-io/evcc/vehicle/skoda/pb"

var (
	file_vehicle_skoda_pb_checkin_proto_rawDescOnce sync.Once
	file_vehicle_skoda_pb_checkin_proto_rawDescData []byte
)

func file_vehicle_skoda_pb_checkin_proto_rawDescGZIP() []byte {
	file_vehicle_skoda_pb_checkin_proto_rawDescOnce.Do(func() {
		file_vehicle_skoda_pb_checkin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vehicle_skoda_pb_checkin_proto_rawDesc), len(file_vehicle_skoda_pb_checkin_proto_rawDesc)))
	})
	return file_vehicle_skoda_pb_checkin_proto_rawDescData
}

var file_vehicle_skoda_pb_checkin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vehicle_skoda_pb_checkin_proto_goTypes = []any{
	(*ChromeBuildProto)(nil),       // 0: skoda.ChromeBuildProto
	(*AndroidCheckinProto)(nil),    // 1: skoda.AndroidCheckinProto
	(*AndroidCheckinRequest)(nil),  // 2: skoda.AndroidCheckinRequest
	(*AndroidCheckinResponse)(nil), // 3: skoda.AndroidCheckinResponse
}
var file_vehicle_skoda_pb_checkin_proto_depIdxs = []int32{
	0, // 0: skoda.AndroidCheckinProto.chrome_build:type_name -> skoda.ChromeBuildProto
	1, // 1: skoda.AndroidCheckinRequest.checkin:type_name -> skoda.AndroidCheckinProto
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vehicle_skoda_pb_checkin_proto_init() }
func file_vehicle_skoda_pb_checkin_proto_init() {
	if File_vehicle_skoda_pb_checkin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vehicle_skoda_pb_checkin_proto_rawDesc), len(file_vehicle_skoda_pb_checkin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vehicle_skoda_pb_checkin_proto_goTypes,
		DependencyIndexes: file_vehicle_skoda_pb_checkin_proto_depIdxs,
		MessageInfos:      file_vehicle_skoda_pb_checkin_proto_msgTypes,
	}.Build()
	File_vehicle_skoda_pb_checkin_proto = out.File
	file_vehicle_skoda_pb_checkin_proto_goTypes = nil
	file_vehicle_skoda_pb_checkin_proto_depIdxs = nil
}
